simp/pupmod-simp-aide

- .fixtures.yml
- .fixtures.yml.local
- .travis.yml
- Gemfile
- manifests/add_rules.pp
- manifests/init.pp
- spec/spec_helper.rb
Updated fixtures, travis.yml, Gemfile.
SIMP-118 #close Update pupmod-simp-aide for travis
> (SIMP-118) Update pupmod-simp-aide for travis

- .fixtures.yml
- .fixtures.yml.local
- build/pupmod-aide.spec
- manifests/to_syslog.pp
Updated to use new rsyslog module format
SIMP-105 #close
> (SIMP 105) Refactor aide module to reflect rsyslog changes

- .fixtures.yml
- .fixtures.yml.local
- README.md
> (SIMP-399) Add link to JIRA and the wiki in README

- .fixtures.yml
- build/pupmod-aide.spec
- manifests/init.pp
- manifests/logrotate.pp
- metadata.json
Initial mapping.  Changes to aide module for compliance mapping.
SIMP-720 #comment
> (SIMP-720) Map 800-53 requirements to hiera

- .travis.yml
- build/pupmod-aide.spec
- manifests/add_rules.pp
- manifests/init.pp
- spec/spec_helper.rb
Tested against Puppet 4 and Ruby 2.1.
Requires updates to simplib.
SIMP-907 #comment Update for Puppet 4 compatibility
> (SIMP-907) Ensure functionality with Puppet 4

- build/rpm_metadata/requires
update the requires file for SIMP6 modules to require
the latest version
SIMP-1735 #comment
> (SIMP-1735) Update Compliance Markup module

- .puppet-lint.rc
- .travis.yml
- CHANGELOG
- build/package_metadata.yaml
- build/rpm_metadata/requires
- metadata.json
updated version and requires files
general housekeeping
(SIMP-2086) #comment
(SIMP-2089) #close
> (SIMP-2086) Bump major version number for aide

- .fixtures.yml
- .puppet-lint.rc
- CHANGELOG
- manifests/add_rules.pp
- manifests/default_rules.pp
- manifests/init.pp
- manifests/logrotate.pp
- manifests/set_schedule.pp
- manifests/syslog.pp
- metadata.json
- types/logfacility.pp
- types/logseverity.pp
- types/rotateperiod.pp
> (SIMP-2288) Strong typed the module.

- build/rpm_metadata/requires
- manifests/logrotate.pp
- metadata.json
updated requires and metadata.json
fixed logrotate "add" call
SIMP-2462 #comment aide updated
> (SIMP-2462) Update Versions

- .fixtures.yml
- CHANGELOG
- Gemfile
- manifests/default_rules.pp
- manifests/init.pp
- manifests/rule.pp
- metadata.json
- spec/classes/init_spec.rb
- spec/defines/rule_spec.rb
Changed calls from auditd::add_rules to auditd::rule
SIMP-2437 #comment Update to latest auditd
> (SIMP-2437) Update to latest auditd

- CHANGELOG
- Gemfile
- manifests/logrotate.pp
- metadata.json
- spec/classes/logrotate_spec.rb
SIMP-2045 #comment aide done
SIMP-3039 #close
> (SIMP-2045) Updated logrotate::rule to use new lastaction API

- .gitlab-ci.yml
> (SIMP-3183) add gitlabci to simp module

- CHANGELOG
- build/rpm_metadata/requires
- metadata.json
Requires newer version of logrotate module.
> (SIMP-3372) aide - deps/changelog cleanup as prep for tagging

- CHANGELOG
- fixed date in CHANGELOG
SIMP-3671 #close
> (SIMP-3671) Fixed Change log in aide

- .travis.yml
- CHANGELOG
- manifests/init.pp
- metadata.json
- spec/acceptance/suites/default/class_spec.rb
- spec/classes/init_spec.rb
SIMP-3928 #close
SIMP-1708 #comment code change
> (SIMP-3928) AIDE should retain the output database

- CHANGELOG
- README.md
- metadata.json
This updates README.md to include puppet strings documentation.
SIMP-1343 #close
> (SIMP-1343) Update README.md from puppet strings

- spec/classes/default_rules_spec.rb
> (SIMP-5181) Add /etc/logorate.simp.d to default rules

- .gitlab-ci.yml
- CHANGELOG
- manifests/init.pp
- spec/acceptance/nodesets/default.yml
- spec/acceptance/nodesets/oel.yml
- spec/acceptance/suites/default/class_spec.rb
SIMP-2971 #comment update aide
> (SIMP-2971) Add $package_ensure

- .gitlab-ci.yml
- .travis.yml
- Gemfile
- normalize static assets
SIMP-5585
> (SIMP-5585) Static Assets

- .gitlab-ci.yml
- CHANGELOG
- SIMP/compliance_profiles/checks.yaml
- data/fips_enabled/is_false/os/CentOS-8.yaml
- data/fips_enabled/is_false/os/OracleLinux-8.yaml
- data/fips_enabled/is_false/os/RedHat-8.yaml
- data/fips_enabled/is_true/os/CentOS-8.yaml
- data/fips_enabled/is_true/os/OracleLinux-8.yaml
- data/fips_enabled/is_true/os/RedHat-8.yaml
- hiera.yaml
- manifests/init.pp
- spec/acceptance/suites/compliance/00_simp_profile_install_spec.rb
- spec/classes/init_spec.rb
- templates/aide.conf.erb
- Remove overrides for aide::aliases on EL8 since it works properly in FIPS mode
SIMP-7558 #close
> [SIMP-7558] Fix aide::aliases for EL8

- CHANGELOG
- metadata.json
[SIMP-9248] # close
[SIMP-9248]: https://simp-project.atlassian.net/browse/SIMP-9248
> (SIMP-9248) aide: allow simp/rsyslog 8.0.0

- data/fips_enabled/is_false/os/Rocky-8.yaml
- data/fips_enabled/is_true/os/Rocky-8.yaml
> (#97) Added hieradata in support of Rocky 8

- .fixtures.yml
- CHANGELOG
- SIMP/compliance_profiles/checks.yaml
- metadata.json
- spec/acceptance/suites/compliance/01_simp_profile_inspec_spec.rb
- spec/acceptance/suites/compliance/10_stig_profile_oscap_spec.rb
Also ensure we're testing against latest upstream modules.
Fixes #116
> Fix use of legacy facts
